### ISSUE TITLE
whether consensus sequences contain reads with poly-T

### ISSUE THREAD

**Issue by ssscj** [ucagenomix/sicelore#26]
Hi, 
Thanks for developing this useful software. 
After the 6th step, generating the consensus sequences, will the complementary reads with poly-T be removed ? Do they contribute to the step of computing consensus sequences? Do the consensus sequences contain reads with poly-T? 

Thank you,

Chujie

**Comment by ucagenomix** [comment]
Hi, no polyT do not contribute to consensus sequence calculation, we remove it from the cDNA sequences before consensus compute using poa (v1) or spoa (v2). But there is still some reads that kept the polyA and you can see some consensus sequence having a polyA. It would be better not to have it before consensus sequence remapping because you may increase a preferential mapping to pseudogenes. Cheers, Kevin.

**Comment by ssscj** [comment]
Thanks for your reply. I have another question that the consensus sequence is the cDNA sequence, so is it reverse complementary  with the mRNA sequence and identical to the template strand on the genome? Thank you.

Best wishes,
Chujie
