### ISSUE TITLE
Error when running IlluminaParser.jar

### ISSUE THREAD

**Issue by jbeaulaurier** [ucagenomix/sicelore#3]
Hello,
I'm encountering the following error while executing this command: 

`java -Xmx15000m -jar IlluminaParser-1.0.jar --inFileIllumina aligned.sorted.bam --tsv illumina_cellbarcodes.tsv --outFile illumina.bam.obj --cellBCflag CB --umiFlag UB --geneFlag GN`

```
..................................................
..................................................
..........................Scan took: 10:58:811
Getting some stats
Exception in thread "main" java.lang.NullPointerException
        at com.rw.bamparsermaven.Parser.parse(Parser.java:149)
        at com.rw.bamparsermaven.Main.main(Main.java:89)
```

Any ideas what could be causing this?
Thanks,
John

**Comment by ucagenomix** [comment]
This error occurred during the generation of some stats(number of UMIs associated with genes) after writing the parsed Illumina data to disk. 
That means the parsed Illumina data were written to disk just some stats were not calculated.
Was the input bam file generated by Cellranger or another pipeline ?
We revised the calculation of the  stats.  Please try it again with today’s build. 
Since one library shared by three jars was modified you need to replace IlluminaParser-1.0.jar , NanoporeBC_UMI_finder-1.0.jar, NanoporeReadScanner-0.5.jar and the entire /lib directory.

**Comment by jbeaulaurier** [comment]
That helped, but now I'm hitting an error a few lines later. And no, this BAM file was not generated using Cell Ranger.
```
..................................................
..........................Scan took: 08:37:930
Getting some stats
Exception in thread "main" java.lang.NullPointerException
        at com.rw.bamparsermaven.Parser.parse(Parser.java:154)
        at com.rw.bamparsermaven.Main.main(Main.java:99)

```

**Comment by ucagenomix** [comment]
It is actually the same error.  I just split one line with a complex sequence of java stream operations into several lines to facilitate the identification of the problem.
This exception suggests that no SAM record with the gene , cell barcode and umi tag you specified in your command line was found in your BAM file.
Since your BAM file was not generated by Cellranger, could you verify whether  the gene name , cell barcode and umi in your SAM records have the GN, CB and UB tags respectively that you defined in the command line.
We added now additional code that verifies whether the BAM file has the tags specified in the command line. Info about not found tags is printed now.
To install the revised code, Just replace IlluminaParser-1.0.jar, no need to replace the lib folder.

 

To identify the reason why your bam file poses problems we would need a few (5 – 10) SAM records from your BAM file.

At least two of those SAM records should have the SAM tags for the gene, cell barcode and umi.

**Comment by jbeaulaurier** [comment]
In the end, I've decided to run CellRanger and this is producing the BAM file with the proper tags. Thanks for your explanations.
