### ISSUE TITLE
Reproducibility of NanoporeBC_UMI_finder

### ISSUE THREAD

**Issue by kwells4** [ucagenomix/sicelore#35]
Hi,

Thank you for creating this great software! The steps are well laid out and easy to follow and I was very impressed with the final output (the UMAPs for the short and long read look nearly identical for highly expressed genes).

I did have a few questions about the BC_UMI finder step. I've been working to ensure my pipeline is reproducible and I noticed that when I rerun the pipeline, I see slight differences in the number of reads after running `NanoporeBC_UMI_finder`. I am currently using the `--maxUMIfalseMatchPercent` and `--maxBCfalseMatchPercent` which I am guessing implements a random seed to dynamically edit the UMI and BC distance. Is there any way to set a seed so that rerunning the pipeline gives identical results? I am currently running as part of a Snakemake pipeline in an Anaconda environment to try to keep variables as consistent as possible.

I also noticed in #15 that you expect over 50% of reads are labeled with a UMI and BC. I also lose a lot of reads and only see about 20% of reads with a polyA tail get assigned a barcode. We did aim for ~3,000 cells and our sequencing saturation in the short read is only ~20%. Do you think sequencing closer to saturation for the short read data could potentially increase our ability to assign UMIs and BCs?

Thanks for your help!
Kristen

**Comment by RainerWaldmann** [comment]
Hi Kristen,

Sorry for the delayed reply. I was running some tests to answer your first question.

Regarding the slight differences in the number of reads.  The thread management of this version can cause an too early stop of a thread when the last processed records require much CPU time. This can lead to the loss of a few BAM records but it DOES NOT lead to a false assignment. Since the order how the threads terminate can vary between runs this might lead to small differences in the counts between runs.
This was fixed in a new version of the software that I'll release soon.

As for the UMI assignment efficiency, ony Nanopore UMIs that were found in the Illumina data are assigned. An Illumina sequencing saturation of 20% means that only 20% of the UMIs were Illumina sequenced.  However, barcode assignment efficiency (without assigned UMI) should be higher than 20% despite the low Illumina sequencing depth.

I'll release til end of June a beta version of a new heavily revised software that combines Illumina guided UMI assignment and UMI assignment by clustering. This will increase assignment efficiency.

Rainer

**Comment by kwells4** [comment]
Hi Rainer,

Thanks for the detailed response, your explanation makes sense regarding the slight differences between runs. The count number was very small (roughly 30 reads different each run). I look forward to the new release!

As for the efficiency, this initial run was just a pilot, so we also have some technical improvements to be made in the nanopore quality. Hopefully between improvements in the data quality on our end and the next version of your pipeline we have higher assignment efficiency!

Again, thanks for your help and writing a great package! I will close as it seems these issues will be answered with your next release.

Kristen
