### ISSUE TITLE
Can not found UMI 

### ISSUE THREAD

**Issue by RyanYip-Kat** [ucagenomix/sicelore#38]
When I run NanoporeBC_UMI_finder.jar, the log file told me that can not find the UMI(0%),how can I fix the issue?Thanks!

**Comment by ucagenomix** [comment]
please copy/paste more log information

**Comment by rajasreemenon** [comment]
Hi, I am running sicelore for integrating ONT long reads with Illumina 10X genomics 3' single cell data. I am able to run successfully till Nanpore UMI BC find step. At this step when I run NanoporeBC_UMI_finder.jar, I am not finding any UMIs. Since I did provide any config.xml separately the default xml in sicelore is being used by the app. Please let me know how I can fix this issue. Thank you!

**Comment by ucagenomix** [comment]
please copy/paste more log information

**Comment by ucagenomix** [comment]
Please visit Sicelore-2.1 github repository for this issue:
https://github.com/ucagenomix/sicelore-2.1
