### ISSUE TITLE
UMI !=12bp,can work

### ISSUE THREAD

**Issue by RyanYip-Kat** [ucagenomix/sicelore#42]
If umi length is not 12bp,can sicelore worked?can it found bc and umi ?

**Comment by RainerWaldmann** [comment]
The software identifies the length of the UMI from the Illumina data. Definitely also works with 10 nt.  UMIs (the older 10X kits). Should also work with other UMI lengths. However you need to use fixed edit distance since the dynamic edit distances (for preset false assignment percentage) are only supplied for 10 nt. and 12 nt. UMIs in umiMaxEditDistances.xml. 

Rainer
