### ISSUE TITLE
Sicelore-2.0.jar ComputeConsensus must split chr ?

### ISSUE THREAD

**Issue by markme123** [ucagenomix/sicelore#44]

**Comment by ucagenomix** [comment]
you can split your cellBC/UMI assigned bam file per chromosome to save time for consensus calling (parralel execution) if one task is too long. Note that you willl have then to deduplicate molecules after cat all chromosome molecules .fastq files, because some reads can multimap across different chromosomes (ie pseudogenes).

**Comment by markme123** [comment]
thanks
