### ISSUE TITLE
Unable to run NanoporeBC_UMI_finder-1.0.jar since Jan 1, 2020 due to python update? 

### ISSUE THREAD

**Issue by ahawkins1992** [ucagenomix/sicelore#6]
Unable to do barcode and UMI assignment using NanoporeBC_UMI_finder-1.0.jar. Getting the following error: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! EXPIRED 2020-01-01 - Download a new version from Github !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This is the command that was used: 
java -jar -Xmx30g /gpfs/commons/home/gmullokandov/software/sicelore/Jar/NanoporeBC_UMI_finder-1.0.jar -i y1_GEUS_ont_got.bam -o y1_lin_ont_got_10xAttributes.bam -k y1_parsed_got.obj --maxUMIfalseMatchPercent 1 --maxBCfalseMatchPercent 5 --logFile y1_lin_ont_got_out_NanoporeBC_UMI_finder.log

Is able to try and fail to start when we change the time to Dec 31, probably due to Python2 not being supported as of 1/1/20? Can you help address this? 

Thanks!
Ally

**Comment by ucagenomix** [comment]
We did some (minor) bug fixes since the initial release of the software. 
We are currently putting an expiry date into the jars on Github to remind users to download a new version that includes the latest bug fixes.
We’ll soon remove this expiry date and switch and to a release of incremental versions of the software.
Just download the files in the Jar/ and /Jar/lib folder and replace the old files against the new ones.
